version: '3'
services:
  kindle_display:
    container_name: kindle_display
    build:
      # context: /usr/local/scripts/kindleDisplay
      context: .
      dockerfile: Dockerfile
    image: result/latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5050:5050"
