services:
  kindle_display:
    container_name: kindle_display
    build:
      context: .
      dockerfile: Dockerfile
    image: result/latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5050:5050"
    environment:
      - FLASK_APP=kindleDisplay
      - FLASK_ENV=development
      - FLASK_DEBUG=1

